# Generated by Django 2.0.1 on 2018-02-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosmundial', '0004_auto_20180221_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apuesta',
            old_name='ganancia',
            new_name='apuesta',
        ),
        migrations.RenameField(
            model_name='apuesta',
            old_name='monto',
            new_name='importe',
        ),
        migrations.RenameField(
            model_name='apuesta',
            old_name='pronostico',
            new_name='resultado',
        ),
    ]
