# Generated by Django 2.0.1 on 2018-02-21 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegosmundial', '0006_datosusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
