# Generated by Django 2.0.1 on 2018-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosmundial', '0007_auto_20180221_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
